name: Build and deploy Python backend to Azure Web App - fashion-python-api

on:
  push:
    branches:
      - main
    paths:
      - "scripts/**"
      - "server/**"
      - "requirements.txt"
      - "scripts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Setup Python for backend ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      # (Optional) build step if backend needs transpile or collectstatic, else skip
      - name: Archive backend
        run: zip -r backend.zip . -x "venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-app

      - name: Unzip
        run: unzip backend.zip -d .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "fashion-python-api" # Azure App Service name
          slot-name: "Production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "."
